variables:
  DOCKER_DRIVE: overlay

services:
  - docker:dind

stages:
  - dependencies
  - stylecheck
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: dependencies
  image: node:8-alpine
  artifacts:
    paths:
      - node_modules/
  before_script:
    - node -v
    - npm -v
    - tsc -v
  script:
    - npm install

do_style_check:
  stage: stylecheck
  image: node:8-alpine
  script:
    - npm run lint
    - npm run prettier:check

run_tests:
  stage: test
  image: node:8-alpine
  script:
    - npm run report

build_source:
  stage: build
  image: node:8-alpine
  script:
    - npm run build