language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install -g typescript
  - npm install

before_script:
  - node -v
  - npm -v
  - tsc -v

stages:
  - stylecheck
  - test
  - build

jobs:
  include:
    - stage: stylecheck
      script: npm run lint && npm run prettier:check
    - stage: test
      script: npm test
    - stage: build
      script: npm run build